### PR TITLE
Fix NPE thrown by MultiValueMap endpoints

### LINKED ISSUE #62: RequestBodyCleaner throws an NPE if channel is null for MultiValueMap "services/collector" endpoint
**Describe the bug**

An NPE is thrown for the endpoint
```java
@RequestMapping(
        value = "services/collector",
        method = RequestMethod.POST,
        consumes = MediaType.APPLICATION_FORM_URLENCODED_VALUE,
        produces = MediaType.APPLICATION_JSON_VALUE
)
public ResponseEntity<JsonNode> sendEvents(
        HttpServletRequest request,
        @RequestBody MultiValueMap body,
        @RequestParam(required = false) String channel
) {
```
**Expected behavior**

Probably the same behavior as the alternative endpoint
```java
@RequestMapping(
        value = "services/collector",
        method = RequestMethod.POST,
        consumes = MediaType.APPLICATION_JSON_VALUE,
        produces = MediaType.APPLICATION_JSON_VALUE
)
public ResponseEntity<JsonNode> sendEvents(
        HttpServletRequest request,
        @RequestBody String eventInJson,
        @RequestParam(required = false) String channel
) {
```
**How to reproduce**

 Send MultiValueMap body to the endpoint without a channel
**Screenshots**

 
**Software version**

 2.0.3
 
**Additional context**

### PR DESCRIPTION
**Pull request by MoonBow-1**
## Description
Closes #62 

- Standardizes MultiValueMap endpoints with the same behavior as JSON endpoints
  - Does not require channel to be present when sending events to MultiValueMap endpoints
- Implements `AcknowledgementResponse` for responses involving acknowledgement
- Adds Apache JMeter test for the `application/x-www-form-urlencoded` sendEvents endpoint

#### General

- [x] I have checked that my test files and functions have meaningful names.
- [x] I have checked that each test tests only a single behavior.
- [x] I have done happy tests.
- [x] I have tested only my own code.
- [x] I have tested at least all public methods.

#### Assertions

- [x] I have checked that my tests use assertions and not runtime overhead.
- [x] I have checked that my tests end in assertions.
- [x] I have checked that there is no comparison statements in assertions.
- [x] I have checked that assertions are in tests and not in helper functions.
- [x] I have checked that assertions for iterables are outside of for loops and both sides of the iteration blocks.
- [x] I have checked that assertions are not tested inside consumers.

#### Testing Data

- [x] I have tested algorithms and anything else with the possibility of unbound growth.
- [x] I have checked that all testing data is local and fully replaceable or reproducible or both.
- [x] I have checked that all test files are standalone.
- [x] I have checked that all test-specific fake objects and classes are in the test directory.
- [x] I have checked that my tests do not contain anything related to customers, infrastructure or users.
- [x] I have checked that my tests do not contain non-generic information.
- [x] I have checked that my tests do not do external requests and are not privately or publicly routable.

#### Statements

- [x] I have checked that my tests do not use throws for exceptions.
- [x] I have checked that my tests do not use try-catch statements.
- [x] I have checked that my tests do not use if-else statements.

#### Java

- [x] I have checked that my tests for Java uses JUnit library.
- [x] I have checked that my tests for Java uses JUnit utilities for parameters.

#### Other

- [x] I have only tested public behavior and not private implementation details.
- [x] I have checked that my tests are not (partially) commented out.
- [x] I have checked that hand-crafted variables in assertions are used accordingly.
- [x] I have tested [Object Equality](https://docs.oracle.com/javase/6/docs/api/java/lang/Object.html#equals%28java.lang.Object%29).
- [x] I have checked that I do not have any manual tests or I have a valid reason for them and I have explained it in the PR description.

### Code Quality

- [x] I have checked that my code follows metrics set in Procedure: Class Metrics.
- [x] I have checked that my code follows metrics set in Procedure: Method Metrics.
- [x] I have checked that my code follows metrics set in Procedure: Object Quality.
- [x] I have checked that my code does not have any NULL values.
- [x] I have checked my code does not contain FIXME or TODO comments.

### CODE REVIEW

**Review by Tiihott — APPROVED** [review]
Tests pass and changes look fine along with the new tests.
The old classes should be refactored at some point to properly add the equals() and hashCode() methods alongside equalsVerifier tests, to make things more OOP.

**Review by Tiihott — DISMISSED** [review]
Tests pass and changes look fine along with the new tests.
The old classes should be refactored at some point to properly add the equals() and hashCode() methods alongside equalsVerifier tests, to make things more OOP.

**Comment by MoonBow-1** [comment]
> Tests pass and changes look fine along with the new tests. The old classes should be refactored at some point to properly add the equals() and hashCode() methods alongside equalsVerifier tests, to make things more OOP.

Issues that relate to the maintainability, which are known/worked on:
#14 
#17 
#33 
#36

File: src/main/java/com/teragrep/cfe_16/MultiValueMapRequest.java [hunk 1]
```diff
@@ -0,0 +1,103 @@
...
+    }
+
+    /**
+     * @return Example of cleaned body: {"sourcetype": "mysourcetype", "event": "Hello, world!"}
+     * @throws IllegalStateException if the MultiValueMap contains more than one key after the channel has been removed
+     */
+    public String asCleanedJsonString() throws IllegalStateException {
+        final String valueToReturn;
+        // Remove the channel, if it is present
+        multiValueMap.remove("channel");
```
Comment (eemhu) [inline src/main/java/com/teragrep/cfe_16/MultiValueMapRequest.java]: Should this be performed on a copy so the original map is not modified?

File: src/test/java/com/teragrep/cfe_16/rest/HECRestControllerTest.java [hunk 2]
```diff
@@ -0,0 +1,195 @@
...
+    void testJsonSendEventsEndpointWithChannelPresent() {
+        final MockHttpServletRequest request1 = new MockHttpServletRequest();
+        request1.addHeader("Authorization", "AUTH_TOKEN_11111");
+        final String channel1 = "CHANNEL_11111";
+        final String eventInJson = "{\"sourcetype\":\"access\", \"source\":\"/var/log/access.log\", "
+                + "\"event\": {\"message\":\"Access log test message 1\"}} "
+                + "{\"sourcetype\":\"access\", \"source\":\"/var/log/access.log\", \"event\": "
+                + "{\"message\":\"Access log test message 2\"}}";
+
+        final ResponseEntity<JsonNode> variable = Assertions
```
Comment (eemhu) [inline src/test/java/com/teragrep/cfe_16/rest/HECRestControllerTest.java]: variable name

File: src/main/java/com/teragrep/cfe_16/MultiValueMapRequest.java (hunk 1 above)
Comment (MoonBow-1) [reply src/main/java/com/teragrep/cfe_16/MultiValueMapRequest.java]: Made sure to not modify the underlying field in commit f7c3ff9d

File: src/test/java/com/teragrep/cfe_16/rest/HECRestControllerTest.java (hunk 2 above)
Comment (MoonBow-1) [reply src/test/java/com/teragrep/cfe_16/rest/HECRestControllerTest.java]: Fixed in commit adebd402

Comment (eemhu) [reply src/test/java/com/teragrep/cfe_16/rest/HECRestControllerTest.java]: there are more instances in the same file left

Comment (MoonBow-1) [reply src/test/java/com/teragrep/cfe_16/rest/HECRestControllerTest.java]: Fixed in commit 25448c9

**Review by eemhu — APPROVED** [review]
